stages:
    - package_install

install packags:
    stage: package_install
    only:
        changes:
            - package/*
    script:
        Rscript /home/ga52cib/gitlabRunnerInstaller/ExpressionSetViewer.R
